version: "3.4"

services:
  espace_admin:
    container_name: espace_admin
    hostname: espace_admin
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile_dev
    volumes: 
      - ./app:/app
      - cert-handler_certbot-letsencrypt:/etc/letsencrypt
    ports:
      - 4200
    stdin_open: true

volumes:
  cert-handler_certbot-letsencrypt:
    external: true

networks: 
  default:
    external:
      name: the_network
